DROP DATABASE IF EXISTS EJERCICIO_JUANDI;
CREATE DATABASE EJERCICIO_JUANDI;
USE EJERCICIO_JUANDI;

 create table empleados(
  documento char(8),
  nombre varchar(20),
  apellido varchar(20),
  sueldo decimal(6,2),
  cantidadhijos int,
  seccion varchar(20),
  primary key(documento)
 );

INSERT INTO EMPLEADOS VALUES('47755045', "ASIER", "CHICHARRO", 999, 5, "LOPO" );
INSERT INTO EMPLEADOS VALUES('27220608', "JORGE", "GUERRERO", 750, 1, "YAYIL" );
INSERT INTO EMPLEADOS VALUES('31789095', "SANTI", "AGO", 990, 3, "LOPO" );
INSERT INTO EMPLEADOS VALUES('47754782', "YAYO", "DAVID", 480, 6, "YAYIL" );

DROP PROCEDURE IF EXISTS PA_EMPLEADOS_SUELDO;

DELIMITER $
CREATE PROCEDURE PA_EMPLEADOS_SUELDO(IN SUEL VARCHAR(50))
BEGIN
SELECT NOMBRE, APELLIDO, SUELDO FROM EMPLEADOS
WHERE SUELDO >= SUEL;
END $
DELIMITER ;

call PA_EMPLEADOS_SUELDO(200);
CALL PA_EMPLEADOS_SUELDO(500);

DROP PROCEDURE IF EXISTS PA_EMPLEADOS_ACTUALIZAR_SUELDO;

DELIMITER $
CREATE PROCEDURE PA_EMPLEADOS_ACTUALIZAR_SUELDO(IN SUEL VARCHAR(50))
BEGIN
SET sueldo = SUEL;
END $
DELIMITER ;

 call pa_empleados_actualizar_sueldo(300, 350);
 select * from empleados;
